version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      frontend:
        aliases:
          - redis
    restart: unless-stopped

  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: unless-stopped

  pulledpork:
    build: .
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis
    restart: unless-stopped

networks:
  frontend:
  backend:

volumes:
  db-data:
